 
from channels.generic.websocket import WebsocketConsumer
import json
import requests
import os
from .rag import QueryInput,generateQuestions
import time
from .ans_based_ques import EvaluationInput,ans_based_ques

# ques = {'answer': "1. Can you share a specific Python project you worked on and describe the problem you were trying to solve? What was the most challenging part of the project, and how did you overcome it?\n        2. You have mentioned developing a backend for a web portal offering internships to students. Can you walk me through the process of designing and implementing the REST APIs for this project? \n        3. In your experience, how have you optimized the performance of your Python code to ensure efficient handling of large volumes of data? Can you provide an example?\n        4. You've worked with Django Rest Framework. Can you describe a scenario where you encountered an error"}



class InterviewConsumer(WebsocketConsumer):
    function_called = True
   
    videoResults = []
    questions = []
    current_question_index = 0
    flag = True
    questionsCount = 0

    def connect(self):
        self.videoResults = []
        self.questions = []        
        self.accept()

    

    def call_function_once(self, file_path, skillsLevel):
        self.flag = False
         
        skills1 = skillsLevel
        print("skills1 ",skills1)
        input_data = QueryInput(topic="Python", file=file_path, skills=skills1)
         
        # ques = generateQuestions(input_data)
        # print("Questions generated by model ", ques)
        print("-----------------------------")
        
    #    you worked on during your internship at General Mills, and explain how you used machine learning to detect anomalies in database metrics using two key indicators? What challenges did you face and how did you overcome them

    
        ques = {'answer': "1. Can you elaborate on a specific Python project you worked on during your internship at General Mills, and explain how you used machine learning to detect anomalies in database metrics using two key indicators? What challenges did you face and how did you overcome them?\n   2. In your project with AWS Cloud Intern, you managed pipelines with CodePipeline, CodeBuild, and CodeDeploy. Can you describe a situation where you had to optimize these pipeline stages to enhance deployment efficiency and reduce downtime? What strategies did you employ, and what were the results?\n 3. In the Netflix Clone DevSecOps project, you integrated SonarQube and Trivy for vulnerability management. Can you share an instance where these tools helped you identify and resolve a critical security issue? How did you approach this problem, and what was the outcome?\n  4. For the AI-Powered Interview Assistant project, you used machine learning and natural language processing. Can you discuss how you implemented the RAG and Mistral models for analyzing resumes and generating tailored interview questions? What challenges did you face in creating a compatible question generation system, and how did you address them?\n 5. You have experience working with multiple libraries and frameworks, including Pandas, Numpy, Django, and Django Rest Framework. Can you share a scenario where you had to leverage the strengths of these libraries and frameworks together to build a robust, scalable, and high-performing solution? What was the outcome, and how did you measure its success? "}

        #  3.   how have you optimized the performance of your Python code ?\n        4.  Can you describe a scenario where you encountered an error

        
         
        if ques:
            self.questions = [q.strip() for q in ques['answer'].split('\n') if q.strip()]
            print("Extracted Questions:", self.questions)
            self.videoResults = []

        else:
            self.questions = ["No questions generated"]

 




    def send_next_question(self):
        print("Inside send next question")
         
        if self.current_question_index < len(self.questions):
            question = self.questions[self.current_question_index]
            self.questionsCount += 1
            self.send(text_data=json.dumps({'question': question, 'result': self.videoResults}))
            self.current_question_index += 1
            print("current_question_index is ", self.questionsCount)
            self.flag = False
             
          
 

    def receive(self, text_data):
         
        python_data = json.loads(text_data)
        client_message = python_data.get('client_mess', '')
        upload_response = python_data.get('result', '')
        resume_path = python_data.get('resume', '')
        skillsLevel = python_data.get('Skills',{})
        user_ans = python_data.get('client_ans', '')
        user_ques = python_data.get('client_ques', '')


        if client_message and self.questionsCount == 2 * len(self.questions):
            print("(9999999999999999999999999999999999999)")
            self.send(text_data=json.dumps({'end': "End of the interview"}))
            return

        # Handling video results
        if upload_response:
            self.videoResults.append(upload_response)
            print("Video Results Updated:", self.videoResults)

            if len(self.videoResults) == self.questionsCount:
                self.send(text_data=json.dumps({'FinalResult': self.videoResults}))
                return   

        # Handle resume upload and question generation
        if resume_path and self.function_called:
            self.call_function_once(resume_path, skillsLevel)
            self.function_called = False
            self.flag = True
            self.send_next_question()
            return

        # Handle sending the next question
        if self.flag and client_message:
            self.send_next_question()
            return

        

      
        if not self.flag and user_ans and user_ques and client_message:
            self.flag = True  
           
            input_data = EvaluationInput(
                question=user_ques,
                candidate_answer=user_ques
            )
            evaluation_result = ans_based_ques(input_data)
            print(evaluation_result)
             
            final_ques = evaluation_result.split("Question: ", 1)[1]
            self.questionsCount += 1
            print("current_question_index is ", self.questionsCount)
            self.send(text_data=json.dumps({'question': final_ques}))
            return
              

        



    def disconnect(self, close_code):
        self.videoResults = []
        self.questions = []
        if len(self.videoResults) != self.questionsCount:
            print("Waiting for all results to be received before disconnecting.")
        else:
            print("WebSocket disconnected")



# daphne AI_Interview_System.asgi:application