 
from channels.generic.websocket import WebsocketConsumer
import json
import requests
import os
from .rag import QueryInput,generateQuestions
import time
from .ans_based_ques import EvaluationInput,ans_based_ques

 # ques = {'answer': "1. Can you share a specific Python project you worked on and describe the problem you were trying to solve? What was the most challenging part of the project, and how did you overcome it?\n        2. You have mentioned developing a backend for a web portal offering internships to students. Can you walk me through the process of designing and implementing the REST APIs for this project? \n        3. In your experience, how have you optimized the performance of your Python code to ensure efficient handling of large volumes of data? Can you provide an example?\n        4. You've worked with Django Rest Framework. Can you describe a scenario where you encountered an error"}



class InterviewConsumer(WebsocketConsumer):
    function_called = True
   
    videoResults = []
    questions = []
    current_question_index = 0
    flag = True

    def connect(self):
        self.videoResults = []
        self.questions = []        
        self.accept()

    

    def call_function_once(self, file_path):
        self.flag = False
        skills1={
            "Python": "Intermediate",
            "Django": "High",
            "JavaScript": "Low"
        }
        input_data = QueryInput(topic="Python", file=file_path, skills=skills1)
         
        ques = generateQuestions(input_data)
        print("Questions generated by model ", ques)
        print("-----------------------------")
        ques = {
            'answer': "1. what is python?\n 2. What is Java?"}
        
       
        if ques:
            self.questions = [q.strip() for q in ques['answer'].split('\n') if q.strip()]
            print("Extracted Questions:", self.questions)
            self.videoResults = []

        else:
            self.questions = ["No questions generated"]

 




    def send_next_question(self):
        print("Inside send next question")
         
        if self.current_question_index < len(self.questions):
            question = self.questions[self.current_question_index]
            self.send(text_data=json.dumps({'question': question, 'result': self.videoResults}))
            self.current_question_index += 1
            self.flag = False
          
 

    def receive(self, text_data):
        print("Flag Value:", self.flag)
        python_data = json.loads(text_data)
        client_message = python_data.get('client_mess', '')
        upload_response = python_data.get('result', '')
        resume_path = python_data.get('resume', '')
        user_ans = python_data.get('client_ans', '')
        user_ques = python_data.get('client_ques', '')

        # Handling video results
        if upload_response:
            self.videoResults.append(upload_response)
            print("Video Results Updated:", self.videoResults)

            if len(self.videoResults) >= 2*len(self.questions):
                self.send(text_data=json.dumps({'FinalResult': self.videoResults}))
                return  # No more questions to process, send final results

        # Handle resume upload and question generation
        if resume_path and self.function_called:
            self.call_function_once(resume_path)
            self.function_called = False
            self.flag = True  # Ready to send the first question
            self.send_next_question()
            return

        # Handle sending the next question
        if self.flag and client_message:
            self.send_next_question()
            return

      
        if not self.flag and user_ans and user_ques:
            self.flag = True  
            # payload = {"question": user_ques, "candidate_answer": user_ans}
            
            # try:
            #     response = requests.post("http://127.0.0.1:5000/evaluate", json=payload)
            #     if response.status_code == 200:
            #         generated_question = response.json().get("generated_question", "")
            #         final_ques = generated_question.split("Question: ", 1)[1]
            #         self.send(text_data=json.dumps({'question': final_ques}))
            #     else:
            #         print(f"Error: Received status code {response.status_code} from API")
            # except requests.RequestException as e:
            #     print(f"API request failed: {e}")
            input_data = EvaluationInput(
                question=user_ques,
                candidate_answer=user_ques
            )
            evaluation_result = ans_based_ques(input_data)
            print(evaluation_result)
             
            final_ques = evaluation_result.split("Question: ", 1)[1]
            self.send(text_data=json.dumps({'question': final_ques}))
              




    def disconnect(self, close_code):
        self.videoResults = []
        self.questions = []
        if len(self.videoResults) != len(self.questions):
            print("Waiting for all results to be received before disconnecting.")
        else:
            print("WebSocket disconnected")




# daphne AI_Interview_System.asgi:application