# Generated by Django 5.1 on 2024-08-17 12:56

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_list', djongo.models.fields.JSONField(default=list)),
            ],
        ),
    ]
