# Generated by Django 5.1 on 2024-08-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0002_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeDataStore',
        ),
    ]
